import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Clock, MapPin } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { LogosBar } from "@/components/logos-bar";
import { attractionsQuery, dateReached, formatDate, nextEditionsQuery, type AttractionView } from "@/lib/site-content";

export const Route = createFileRoute("/programacao")({
  validateSearch: (search: Record<string, unknown>) => ({ edicao: typeof search.edicao === "string" ? search.edicao : undefined }),
  head: () => ({ meta: [{ title: "Programação — Festival Aviva Cultura" },{ name: "description", content: "Atrações, horários e locais das próximas edições do Festival Aviva Cultura." },{ property: "og:title", content: "Programação — Festival Aviva Cultura" },{ property: "og:description", content: "Escolha uma edição e confira sua programação." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: ProgramPage,
});
function ProgramPage() {
  const search = Route.useSearch(); const { data: all = [] } = useQuery(nextEditionsQuery()); const editions = all.filter((item) => item.cidade || item.data_evento || item.locais.length); const selected = editions.find((item) => item.id === search.edicao) ?? editions[0];
  const { data: attractions = [], isLoading } = useQuery(attractionsQuery(selected?.id ?? "")); const visible = Boolean(selected && dateReached(selected.programacao_data));
  const byDay = attractions.reduce<Record<string, AttractionView[]>>((acc,item)=>{ (acc[item.data ?? "sem-data"] ??= []).push(item); return acc; },{}); const days=Object.keys(byDay).sort(); const cover=selected?.capasUrls[0];
  return <SiteShell><section className="relative overflow-hidden bg-brand-purple text-primary-foreground">{cover && <div className="relative aspect-[4/3] md:absolute md:inset-0 md:aspect-auto"><img src={cover} alt={`Identidade visual da edição em ${selected?.cidade ?? ""}`} className="size-full object-cover"/></div>}{cover && <div className="hidden md:absolute md:inset-0 md:block md:bg-gradient-to-r md:from-brand-purple md:via-brand-purple/80 md:to-brand-purple/10"/>}<div className={`relative mx-auto flex max-w-7xl items-center px-5 py-14 md:px-8 md:py-20 ${cover ? "md:min-h-[58svh]" : ""}`}><div><p className="text-sm font-bold uppercase text-brand-yellow">Programação</p><h1 className="mt-4 max-w-4xl font-display text-4xl uppercase leading-none md:text-7xl">{selected?.cidade ? `Aviva Cultura em ${selected.cidade}` : "Em breve"}</h1></div></div></section>
  {editions.length > 1 && <nav className="border-b bg-brand-cream"><div className="mx-auto flex max-w-5xl gap-2 overflow-x-auto px-5 py-4 md:px-8">{editions.map((edition)=><Link key={edition.id} to="/programacao" search={{edicao:edition.id}} className={`shrink-0 px-4 py-2 text-sm font-bold uppercase ${edition.id===selected?.id ? "bg-brand-pink text-primary-foreground" : "border border-border bg-background"}`}>{edition.cidade || "Edição"}</Link>)}</div></nav>}
  <section className="py-16 md:py-24"><div className="mx-auto max-w-5xl px-5 md:px-8">{!selected ? <div className="text-center"><h2 className="font-display text-5xl uppercase text-brand-pink">Em breve</h2></div> : !visible ? <div className="border border-dashed p-12 text-center"><h2 className="font-display text-4xl uppercase text-brand-pink md:text-6xl">Aguarde</h2><p className="mt-4 text-lg text-muted-foreground">{selected.programacao_data ? `A programação será divulgada em ${formatDate(selected.programacao_data)}.` : "A programação será divulgada em breve."}</p></div> : isLoading ? <p>Carregando programação...</p> : attractions.length===0 ? <div className="border border-dashed p-12 text-center"><h2 className="font-display text-4xl uppercase text-brand-pink">Em breve</h2></div> : <div className="space-y-12">{days.map((day)=><div key={day}><h2 className="font-display text-2xl uppercase text-brand-pink md:text-3xl">{day==="sem-data"?"Datas a confirmar":formatDate(day)}</h2><div className="mt-6 divide-y border-t">{byDay[day].map((item)=><article key={item.id} className="flex flex-col gap-4 py-6 md:flex-row md:gap-8">{item.horario&&<p className="shrink-0 font-display text-xl text-brand-teal md:w-24">{item.horario.slice(0,5)}</p>}{item.imagemUrl&&<img src={item.imagemUrl} alt={item.nome} className="aspect-[4/3] w-full object-cover md:size-40"/>}<div><h3 className="font-display text-xl uppercase md:text-2xl">{item.nome}</h3>{item.local&&<p className="mt-1 flex gap-2 text-sm text-muted-foreground"><MapPin className="size-4"/>{item.local}</p>}{item.descricao&&<p className="mt-3 text-lg leading-relaxed text-foreground/80">{item.descricao}</p>}{!item.horario&&<p className="mt-2 flex gap-2 text-xs uppercase text-muted-foreground"><Clock className="size-3"/>horário a confirmar</p>}</div></article>)}</div></div>)}</div>}</div></section><LogosBar url={selected?.logosUrl}/></SiteShell>;
}
