import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { ArrowDown, ArrowUp, FileText, Pencil, Plus, Trash2, Upload, X } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { fetchNextEditions, formatPeriod, type NextEdition, type NextEditionRow } from "@/lib/site-content";
import { SITE_BUCKET, removeFile, signPaths, uploadFile } from "@/lib/storage";
import { Card, FField, ghostBtn, inputCls, primaryBtn } from "./ui";

type FormState = { cidade: string; dataEvento: string; dataFim: string; locais: string[]; inscricoesAbertura: string; inscricoesEncerramento: string; programacaoData: string; possuiOficinas: boolean };
const emptyForm: FormState = { cidade: "", dataEvento: "", dataFim: "", locais: [], inscricoesAbertura: "", inscricoesEncerramento: "", programacaoData: "", possuiOficinas: false };

export function NextEditionPanel() {
  const queryClient = useQueryClient();
  const [editions, setEditions] = useState<NextEdition[]>([]);
  const [row, setRow] = useState<NextEdition | null>(null);
  const [form, setForm] = useState<FormState>(emptyForm);
  const [novoLocal, setNovoLocal] = useState("");
  const [capasUrls, setCapasUrls] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const dirty = useRef(false);
  const set = <K extends keyof FormState>(k: K, v: FormState[K]) => { dirty.current = true; setForm((f) => ({ ...f, [k]: v })); };
  const populate = async (data: NextEdition) => {
    setRow(data); setCapasUrls(await signPaths(SITE_BUCKET, data.capas ?? []));
    setForm({ cidade: data.cidade ?? "", dataEvento: data.data_evento ?? "", dataFim: data.data_fim ?? "", locais: data.locais ?? [], inscricoesAbertura: data.inscricoes_abertura ?? "", inscricoesEncerramento: data.inscricoes_encerramento ?? "", programacaoData: data.programacao_data ?? "", possuiOficinas: data.possui_oficinas });
    dirty.current = false;
  };
  const load = async (selectedId?: string) => {
    const data = await fetchNextEditions(); setEditions(data);
    const selected = data.find((item) => item.id === selectedId) ?? (row ? data.find((item) => item.id === row.id) : null);
    if (selected) await populate(selected); else { setRow(null); setForm(emptyForm); setCapasUrls({}); }
  };
  useEffect(() => { void load(); }, []);
  const persist = async (patch: Partial<NextEditionRow>) => {
    if (!row) return false;
    const { error } = await supabase.from("next_edition").update(patch).eq("id", row.id);
    if (error) { toast.error(error.message); return false; }
    await queryClient.invalidateQueries({ queryKey: ["next-editions"] }); await queryClient.invalidateQueries({ queryKey: ["next-edition"] }); return true;
  };
  const saveAll = async (event: React.FormEvent) => { event.preventDefault(); if (!row) return; setSaving(true); const ok = await persist({ cidade: form.cidade.trim() || null, data_evento: form.dataEvento || null, data_fim: form.dataFim || null, locais: form.locais.filter(Boolean), inscricoes_abertura: form.inscricoesAbertura || null, inscricoes_encerramento: form.inscricoesEncerramento || null, programacao_data: form.programacaoData || null, possui_oficinas: form.possuiOficinas }); setSaving(false); if (ok) { toast.success("Edição atualizada."); await load(row.id); } };
  const createEdition = async () => { const { data, error } = await supabase.from("next_edition").insert({ locais: [], capas: [], possui_oficinas: false }).select("id").single(); if (error) return toast.error(error.message); await load(data.id); toast.success("Nova edição criada. Complete as informações."); };
  const deleteEdition = async (edition: NextEdition) => { if (!confirm(`Excluir a próxima edição ${edition.cidade ?? "sem cidade"} e seus dados relacionados?`)) return; const files = [...edition.capas, edition.regulamento_url, edition.logos_url].filter(Boolean) as string[]; const { error } = await supabase.from("next_edition").delete().eq("id", edition.id); if (error) return toast.error(error.message); await Promise.all(files.map((path) => removeFile(SITE_BUCKET, path))); if (row?.id === edition.id) setRow(null); await load(); toast.success("Edição excluída."); };
  const addCapas = async (files: File[]) => { if (!files.length || !row) return; try { const paths = [...row.capas]; for (const file of files) paths.push(await uploadFile(SITE_BUCKET, `edicoes/${row.id}/capas`, file)); if (await persist({ capas: paths })) await load(row.id); } catch (e) { toast.error(e instanceof Error ? e.message : "Falha no upload."); } };
  const removeCapa = async (path: string) => { if (!row) return; if (await persist({ capas: row.capas.filter((p) => p !== path) })) { await removeFile(SITE_BUCKET, path); await load(row.id); } };
  const moveCapa = async (index: number, delta: number) => { if (!row) return; const target = index + delta; if (target < 0 || target >= row.capas.length) return; const paths = [...row.capas]; [paths[index], paths[target]] = [paths[target], paths[index]]; if (await persist({ capas: paths })) await load(row.id); };
  const uploadSingle = async (file: File, field: "regulamento_url" | "logos_url", current: string | null) => { if (!row) return; try { const folder = field === "logos_url" ? "logos" : "regulamento"; const path = await uploadFile(SITE_BUCKET, `edicoes/${row.id}/${folder}`, file); if (await persist({ [field]: path })) { if (current) await removeFile(SITE_BUCKET, current); await load(row.id); toast.success("Arquivo enviado."); } } catch (e) { toast.error(e instanceof Error ? e.message : "Falha no upload."); } };
  const removeSingle = async (field: "regulamento_url" | "logos_url", current: string | null) => { if (!current || !row) return; if (await persist({ [field]: null })) { await removeFile(SITE_BUCKET, current); await load(row.id); } };
  const addLocal = () => { const value = novoLocal.trim(); if (!value) return; set("locais", [...form.locais, value]); setNovoLocal(""); };

  if (!row) return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl">Próximas edições</h2><p className="text-sm text-muted-foreground">Cadastre cada cidade separadamente.</p></div><button onClick={() => void createEdition()} className={primaryBtn}><Plus className="mr-1 inline size-4" />Nova edição</button></div>{editions.length === 0 ? <p className="rounded-3xl border border-dashed bg-card p-10 text-center text-muted-foreground">Nenhuma próxima edição cadastrada. O site mostra “Em breve”.</p> : <EditionList editions={editions} onEdit={(item) => void populate(item)} onDelete={(item) => void deleteEdition(item)} />}</div>;

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={() => setRow(null)} className="mb-2 text-sm font-semibold text-brand-pink">← Voltar à lista</button><h2 className="font-display text-2xl">{row.cidade || "Nova edição"}</h2></div><button onClick={() => void deleteEdition(row)} className="rounded-full border border-destructive/30 px-4 py-2 text-sm font-semibold text-destructive"><Trash2 className="mr-1 inline size-4" />Excluir</button></div>
    <form onSubmit={saveAll} className="space-y-6">
      <Card title="O anúncio" description="Cidade, locais e período exibidos na página pública."><FField label="Cidade"><input value={form.cidade} onChange={(e) => set("cidade", e.target.value)} className={inputCls} /></FField><div className="mt-4 grid gap-4 md:grid-cols-2"><FField label="Início da edição"><input type="date" value={form.dataEvento} onChange={(e) => set("dataEvento", e.target.value)} className={inputCls} /></FField><FField label="Término da edição"><input type="date" value={form.dataFim} onChange={(e) => set("dataFim", e.target.value)} className={inputCls} /></FField></div><div className="mt-4"><span className="mb-1 block text-xs font-semibold uppercase text-muted-foreground">Locais</span>{form.locais.map((local, i) => <div key={i} className="mb-2 flex gap-2"><input value={local} onChange={(e) => set("locais", form.locais.map((l, idx) => idx === i ? e.target.value : l))} className={inputCls}/><button type="button" onClick={() => set("locais", form.locais.filter((_, idx) => idx !== i))} className="p-2 text-destructive"><Trash2 className="size-4"/></button></div>)}<div className="flex gap-2"><input value={novoLocal} onChange={(e) => setNovoLocal(e.target.value)} placeholder="Novo local" className={inputCls}/><button type="button" onClick={addLocal} className={ghostBtn}><Plus className="size-4"/></button></div></div></Card>
      <Card title="Período de inscrições"><div className="grid gap-4 md:grid-cols-2"><FField label="Início das inscrições"><input type="date" value={form.inscricoesAbertura} onChange={(e) => set("inscricoesAbertura", e.target.value)} className={inputCls}/></FField><FField label="Término das inscrições"><input type="date" value={form.inscricoesEncerramento} onChange={(e) => set("inscricoesEncerramento", e.target.value)} className={inputCls}/></FField></div></Card>
      <Card title="Programação"><FField label="Data de divulgação"><input type="date" value={form.programacaoData} onChange={(e) => set("programacaoData", e.target.value)} className={inputCls}/></FField></Card>
      <Card title="Oficinas"><FField label="Haverá oficinas?"><select value={form.possuiOficinas ? "sim" : "nao"} onChange={(e) => set("possuiOficinas", e.target.value === "sim")} className={inputCls}><option value="nao">Não</option><option value="sim">Sim</option></select></FField></Card>
      <button disabled={saving} className={primaryBtn}>{saving ? "Salvando..." : "Salvar informações"}</button>
    </form>
    <Card title="Imagens de capa" description="A primeira imagem identifica esta edição também na programação."><label className={ghostBtn + " inline-flex cursor-pointer items-center gap-2"}><Upload className="size-4"/>Adicionar imagens<input type="file" accept="image/*" multiple className="hidden" onChange={(e) => { const files = Array.from(e.target.files ?? []); e.target.value = ""; void addCapas(files); }}/></label>{row.capas.length > 0 && <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{row.capas.map((path, i) => <div key={path} className="rounded-2xl border p-2">{capasUrls[path] && <img src={capasUrls[path]} alt={`Capa ${i + 1}`} className="aspect-video w-full rounded-xl object-cover"/>}<div className="mt-2 flex justify-between"><span className="text-xs">{i === 0 ? "CAPA PRINCIPAL" : `#${i + 1}`}</span><div className="flex gap-1"><button onClick={() => void moveCapa(i,-1)}><ArrowUp className="size-4"/></button><button onClick={() => void moveCapa(i,1)}><ArrowDown className="size-4"/></button><button onClick={() => void removeCapa(path)} className="text-destructive"><X className="size-4"/></button></div></div></div>)}</div>}</Card>
    <Card title="Regulamento (PDF)">{row.regulamentoUrl && <a href={row.regulamentoUrl} target="_blank" rel="noreferrer" className="text-sm font-semibold text-brand-pink underline"><FileText className="mr-1 inline size-4"/>Ver regulamento atual</a>}<div className="mt-3 flex gap-2"><label className={ghostBtn + " cursor-pointer"}><Upload className="mr-1 inline size-4"/>{row.regulamento_url ? "Substituir PDF" : "Enviar PDF"}<input type="file" accept="application/pdf" className="hidden" onChange={(e) => { const file=e.target.files?.[0]; e.target.value=""; if(file) void uploadSingle(file,"regulamento_url",row.regulamento_url); }}/></label>{row.regulamento_url && <button onClick={() => void removeSingle("regulamento_url",row.regulamento_url)} className="text-destructive">Remover</button>}</div></Card>
    <Card title="Barra de logos">{row.logosUrl && <img src={row.logosUrl} alt="Barra de logos" className="w-full border object-contain p-3"/>}<div className="mt-3 flex gap-2"><label className={ghostBtn + " cursor-pointer"}><Upload className="mr-1 inline size-4"/>{row.logos_url ? "Substituir barra" : "Enviar barra"}<input type="file" accept="image/*" className="hidden" onChange={(e) => { const file=e.target.files?.[0]; e.target.value=""; if(file) void uploadSingle(file,"logos_url",row.logos_url); }}/></label>{row.logos_url && <button onClick={() => void removeSingle("logos_url",row.logos_url)} className="text-destructive">Remover</button>}</div></Card>
  </div>;
}

function EditionList({ editions, onEdit, onDelete }: { editions: NextEdition[]; onEdit: (item: NextEdition) => void; onDelete: (item: NextEdition) => void }) { return <div className="grid gap-4 md:grid-cols-2">{editions.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border bg-card">{item.capasUrls[0] && <img src={item.capasUrls[0]} alt="" className="aspect-video w-full object-cover"/>}<div className="p-5"><h3 className="font-display text-xl">{item.cidade || "Edição sem cidade"}</h3><p className="mt-1 text-sm text-muted-foreground">{formatPeriod(item.data_evento,item.data_fim) || "Período não informado"}</p><div className="mt-4 flex gap-2"><button onClick={() => onEdit(item)} className={primaryBtn}><Pencil className="mr-1 inline size-4"/>Editar</button><button onClick={() => onDelete(item)} className="rounded-full border border-destructive/30 px-4 py-2 text-destructive"><Trash2 className="size-4"/></button></div></div></article>)}</div>; }
