/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProximaEdicaoRouteImport } from './routes/proxima-edicao'
import { Route as OFestivalRouteImport } from './routes/o-festival'
import { Route as EdicoesAnterioresRouteImport } from './routes/edicoes-anteriores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximaEdicaoRoute = ProximaEdicaoRouteImport.update({
  id: '/proxima-edicao',
  path: '/proxima-edicao',
  getParentRoute: () => rootRouteImport,
} as any)
const OFestivalRoute = OFestivalRouteImport.update({
  id: '/o-festival',
  path: '/o-festival',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesAnterioresRoute = EdicoesAnterioresRouteImport.update({
  id: '/edicoes-anteriores',
  path: '/edicoes-anteriores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EdicoesAnterioresRoute: typeof EdicoesAnterioresRoute
  OFestivalRoute: typeof OFestivalRoute
  ProximaEdicaoRoute: typeof ProximaEdicaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxima-edicao': {
      id: '/proxima-edicao'
      path: '/proxima-edicao'
      fullPath: '/proxima-edicao'
      preLoaderRoute: typeof ProximaEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-festival': {
      id: '/o-festival'
      path: '/o-festival'
      fullPath: '/o-festival'
      preLoaderRoute: typeof OFestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes-anteriores': {
      id: '/edicoes-anteriores'
      path: '/edicoes-anteriores'
      fullPath: '/edicoes-anteriores'
      preLoaderRoute: typeof EdicoesAnterioresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EdicoesAnterioresRoute: EdicoesAnterioresRoute,
  OFestivalRoute: OFestivalRoute,
  ProximaEdicaoRoute: ProximaEdicaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
