/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProximaEdicaoRouteImport } from './routes/proxima-edicao'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as PatrocinioRouteImport } from './routes/patrocinio'
import { Route as OFestivalRouteImport } from './routes/o-festival'
import { Route as EdicoesAnterioresRouteImport } from './routes/edicoes-anteriores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EdicoesIdRouteImport } from './routes/edicoes.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximaEdicaoRoute = ProximaEdicaoRouteImport.update({
  id: '/proxima-edicao',
  path: '/proxima-edicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinioRoute = PatrocinioRouteImport.update({
  id: '/patrocinio',
  path: '/patrocinio',
  getParentRoute: () => rootRouteImport,
} as any)
const OFestivalRoute = OFestivalRouteImport.update({
  id: '/o-festival',
  path: '/o-festival',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesAnterioresRoute = EdicoesAnterioresRouteImport.update({
  id: '/edicoes-anteriores',
  path: '/edicoes-anteriores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesIdRoute = EdicoesIdRouteImport.update({
  id: '/edicoes/$id',
  path: '/edicoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/edicoes/$id': typeof EdicoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/edicoes/$id': typeof EdicoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/edicoes-anteriores': typeof EdicoesAnterioresRoute
  '/o-festival': typeof OFestivalRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/proxima-edicao': typeof ProximaEdicaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/edicoes/$id': typeof EdicoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/patrocinio'
    | '/programacao'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
    | '/edicoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/patrocinio'
    | '/programacao'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
    | '/edicoes/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contato'
    | '/dashboard'
    | '/edicoes-anteriores'
    | '/o-festival'
    | '/patrocinio'
    | '/programacao'
    | '/proxima-edicao'
    | '/reset-password'
    | '/sitemap.xml'
    | '/edicoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  EdicoesAnterioresRoute: typeof EdicoesAnterioresRoute
  OFestivalRoute: typeof OFestivalRoute
  PatrocinioRoute: typeof PatrocinioRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  ProximaEdicaoRoute: typeof ProximaEdicaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EdicoesIdRoute: typeof EdicoesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxima-edicao': {
      id: '/proxima-edicao'
      path: '/proxima-edicao'
      fullPath: '/proxima-edicao'
      preLoaderRoute: typeof ProximaEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinio': {
      id: '/patrocinio'
      path: '/patrocinio'
      fullPath: '/patrocinio'
      preLoaderRoute: typeof PatrocinioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-festival': {
      id: '/o-festival'
      path: '/o-festival'
      fullPath: '/o-festival'
      preLoaderRoute: typeof OFestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes-anteriores': {
      id: '/edicoes-anteriores'
      path: '/edicoes-anteriores'
      fullPath: '/edicoes-anteriores'
      preLoaderRoute: typeof EdicoesAnterioresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/$id': {
      id: '/edicoes/$id'
      path: '/edicoes/$id'
      fullPath: '/edicoes/$id'
      preLoaderRoute: typeof EdicoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  EdicoesAnterioresRoute: EdicoesAnterioresRoute,
  OFestivalRoute: OFestivalRoute,
  PatrocinioRoute: PatrocinioRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  ProximaEdicaoRoute: ProximaEdicaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EdicoesIdRoute: EdicoesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
