-- Preserve the complete edition texts from the original Festival Aviva Cultura website.
BEGIN;
UPDATE public.editions SET descricao = 'O festival em Ibitinga aconteceu em um espaço emblemático da cidade, o Teatro Municipal Darci de Biazi, sendo o primeiro grande evento no equipamento público inaugurado em dezembro do ano passado de 2024.

O evento contou com três dias de programação diversificada, com música, dança, cinema, exposições, artesanato e oficinas de dança cigana e composição coletiva, promovendo o intercâmbio cultural e valorização do talento de artistas locais de diferentes eixos.', imagem_url = NULL WHERE titulo = 'Ibitinga – SP';
UPDATE public.editions SET descricao = 'O Aviva Cultura, já consagrado em São Paulo, e com o patrocínio da Regional Telhas, fez as malas e levou sua energia contagiante ao Mato Grosso do Sul! Na vibrante Praça do Peixe, o evento ofereceu uma programação repleta de cultura local, com espetáculos de música, teatro, dança e emocionantes aulas de breaking dance. Em apenas dois dias, o público chegou a 500 pessoas, com 200 participantes nas oficinas, celebrando a arte em grande estilo!', imagem_url = NULL WHERE titulo = 'Bataguassu – MS';
UPDATE public.editions SET descricao = 'Com o patrocínio da Zilor , a edição, realizada na vibrante Praça da Fonte, foi um verdadeiro sucesso! Além de atrair um público estimado em 450 pessoas, reuniu 155 alunos de escolas municipais que mergulharam na programação da Mostra. Foi um momento de enriquecimento cultural inesquecível! O evento trouxe apresentações de dança, teatro e uma oficina de dança, encantando a todos e deixando a praça repleta de energia e entusiasmo.', imagem_url = NULL WHERE titulo = 'Quatá – SP';
UPDATE public.editions SET descricao = 'Patrocinado pela Santa Massa e Regional Telhas, em março, foi a vez de Assis brilhar com o Aviva Cultura na icônica Concha Acústica Cornélio Fortuna “O Maestro”. Uma programação diversificada, repleta de talentos locais, garantiu momentos de pura cultura e entretenimento para todas as idades. O destaque? Mais de 250 alunos participaram das oficinas, realizadas em duas escolas públicas do município, transformando a cidade em um verdadeiro palco de aprendizado e inspiração!', imagem_url = NULL WHERE titulo = 'Assis – SP';
UPDATE public.editions SET descricao = 'Com o patrocínio da Zilor, essa edição, assim como a de Lençóis Paulista, brilhou com uma programação diversa e cativante. Foram cinco espetáculos de teatro, abrangendo as modalidades infantil, juvenil, adulto e teatro de bonecos, além de uma oficina de bonecos que encantou a todos! Cada evento foi uma celebração do talento dos artistas locais, fortalecendo e enaltecendo a riqueza cultural da região.', imagem_url = NULL WHERE titulo = 'Macatuba – SP';
UPDATE public.editions SET descricao = 'Patrocinado pela Zilor, essa edição, como a de Macatuba, trouxe uma encantadora diversidade com cinco espetáculos de teatro nas modalidades infantil, juvenil, adulto e teatro de bonecos, além de uma oficina de bonecos maravilhosa! A programação foi envolvente, destacando o talento dos artistas locais. Em 21 de outubro de 2022, 24 alunos da rede pública participaram da Oficina de Bonecos no Espaço Cultural Cidade do Livro.', imagem_url = NULL WHERE titulo = 'Lençóis Paulista – SP';
UPDATE public.editions SET descricao = 'Com o patrocínio do Supermercado Confiança, nesta edição, de 5 a 7 de agosto de 2022, a cidade vibrará com a energia de sete talentosos artistas em artes visuais, música e performance. As apresentações ocorrerão no Teatro Municipal Teotônio Vilela, no Parque das Águas e no CEU das Artes, transformando cada espaço em um palco de criatividade e emoção. A Mostra celebra os artistas locais, oferecendo à população a chance de prestigiar o rico patrimônio cultural da cidade.', imagem_url = NULL WHERE titulo = 'Sorocaba – SP';
UPDATE public.editions SET descricao = 'Com uma programação artística deslumbrante, e com o patrocínio da Santa Massa e do Supermercado Avenida, Santa Cruz do Rio Pardo está pronta para um evento memorável! Nos dias 10, 11 e 12 de junho de 2022, a Praça Leônidas será o palco de uma celebração mágica, onde cada artista receberá o reconhecimento e carinho que merece. Venha vivenciar a cidade pulsando com a arte e fazer parte deste espetáculo inesquecível!', imagem_url = NULL WHERE titulo = 'Santa Cruz do Rio Pardo – SP';
UPDATE public.editions SET descricao = 'Patrocinado pela Activas, nos dias 19 e 20 de março de 2022, o Aviva Cultura reuniu diversos artistas no Parque da Juventude, em São Bernardo do Campo. O evento celebrou talentos artísticos locais, dando visibilidade e destaque às expressões criativas da cidade. Dança, teatro, circo e exposições enriqueceram ainda mais essa grande festa cultural.', imagem_url = NULL WHERE titulo = 'São Bernardo do Campo – SP';
UPDATE public.editions SET descricao = 'Nos dias 25 e 26 de março de 2022, a Estação Cidadania de Pindamonhangaba foi palco de uma edição especial do Aviva Cultura. Artistas de diversos segmentos, determinados a mostrar seus talentos, foram selecionados por uma curadoria atenta. Patrocinado pela Total BR, o evento apresentou uma rica variedade de expressões artísticas, com teatro, dança, artes plásticas e música, destacando a força cultural da região.', imagem_url = NULL WHERE titulo = 'Pindamonhangaba – SP';
UPDATE public.editions SET descricao = 'Com o patrocínio do Covabra Supermercados, nos dias 8 e 9 de novembro de 2019, a Praça do Jardim Macarenko, em Sumaré, se transformou em um palco cultural com a Mostra Aviva Cultura. Apresentações de dança, teatro, circo, moda, música e artes plásticas, além de uma exposição impactante com sete pinturas e cinco gravuras, revelaram a visão do artista sobre a realidade, pensamento e críticas sociais.', imagem_url = NULL WHERE titulo = 'Sumaré – SP';
UPDATE public.editions SET descricao = 'Patrocinado pela Activas e com uma programação diversificada, a edição de 29 e 30 de junho de 2019 no Parque Espaço Verde Chico Mendes trouxe arte para todos: samba contagiante, hip hop pulsante e o som marcante da banda marcial. Dança cigana, dança infantil, circo, teatro infantil, histórias, bordado, fotografia e pinturas a óleo completaram o banquete cultural.', imagem_url = NULL WHERE titulo = 'São Caetano do Sul – SP';
UPDATE public.editions SET descricao = 'Com o patrocínio da GR Química e Suall, a primeira edição do Aviva Cultura iluminou a Praça 9 de Julho e o Museu Maj. Novaes nos dias 25, 26 e 27 de janeiro de 2019, com um espetáculo vibrante de teatro, música, circo, dança e artes plásticas. Workshops envolventes de fotografia, anime e circo também atraíram públicos de todas as idades, transformando a cidade em um palco de talentos e criatividade!', imagem_url = NULL WHERE titulo = 'Cruzeiro – SP';
UPDATE public.editions SET descricao = 'Com o apoio da Santa Massa, a edição de Belo Horizonte foi um grande sucesso! O evento contou com a presença de mais de 600 pessoas e reuniu mais de 80 alunos de escolas municipais, que participaram das oficinas oferecidas pelo festival, transformando a escola em um espaço de arte e cultura. O público do Teatro Raul Machado se encantou com as apresentações de dança e teatro. Foi uma experiência cultural marcante!', imagem_url = NULL WHERE titulo = 'Belo Horizonte – MG';
COMMIT;
